---
title: "Analysis on Asia Data"
author: "Megha"
date: "March 7, 2018"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r include=FALSE, cache=FALSE}
#loading the packages
install.packages("bnlearn")
library(bnlearn)
source("http://bioconductor.org/biocLite.R")
biocLite("Rgraphviz")
library(Rgraphviz)
library(ggplot2)
source("https://bioconductor.org/biocLite.R")  ##Use to load gRain package since RBGL is removed from CRAN repository
biocLite("RBGL")
library(gRain) 
library(gRbase)
```

```{r}
# load the data.
data(asia)
# create and plot the network structure.
dag_asia = model2network("[A][S][T|A][L|S][B|S][D|B:E][E|T:L][X|E]")
```

```{r}
#Sampling some observational data points from asia dataset
asia_mut1_obs = asia[sample(nrow(asia), 1600), ]

#intitializing additional column for Intervened target
Int_col = 0

#Adding the INT column
asia_mut1_obs$INT = Int_col
```

```{r}
#First we start by learning parameters of the Bayesian Network given the DAG
fitted = bn.fit(dag_asia, asia, method = "bayes")
```

# Performing queries using gRain package on a mutilated Bayesian Network where we performed a perfect intervention by setting Lung cancer as "Yes". This is similar to a lab experiment where we intervene L like a knock-out experiment in the real world.

```{r}
#Adding perfect intervening at node "L"
asia_mut1_network = mutilated(fitted, evidence = list(L = "no"))
jmutilated = compile(as.grain(asia_mut1_network))

#Sampling experimental data
asia_mut1_exp = rbn(asia_mut1_network,400)

#Intitializing additional column for Intervened target
Int_col = 4

#Adding the INT column
asia_mut1_exp$INT = Int_col
```

```{r}
#Combining observation and experiment into one dataframe
asia_mut1 = rbind(asia_mut1_obs, asia_mut1_exp)
```
